package agent

import (
	"database/sql"
	"errors"
	"strings"
	"time"

	"github.com/GHOSTEDDIE/nexshell/internal/domain"
	"github.com/GHOSTEDDIE/nexshell/internal/localfiles"
)

type localAttachment struct {
	Path    string `json:"path"`
	GrantID string `json:"grant_id"`
}

// SubmitFiles is a user-input boundary. Only the desktop composer can supply files;
// paths discovered in tool results or generated by the model do not enter here.
func (s *Service) SubmitFiles(id, text string, paths []string) error {
	if len(paths) == 0 {
		return s.Submit(id, text)
	}
	var task domain.Task
	if err := s.Store.Load("tasks", id, &task); err != nil {
		return err
	}
	if !time.Now().Before(task.Grant.ExpiresAt) {
		return errors.New("请重新确认任务范围后恢复")
	}
	var inputs []localAttachment
	seen := map[string]bool{}
	for _, p := range paths {
		real, err := localfiles.ResolveReference(p)
		if err != nil {
			return err
		}
		if seen[real] {
			continue
		}
		seen[real] = true
		inputs = append(inputs, localAttachment{Path: real, GrantID: task.Grant.ID})
	}
	for _, input := range inputs {
		if err := s.Store.Put("local_inputs:"+id, domain.Digest(input.Path), input); err != nil {
			return err
		}
	}
	var message strings.Builder
	message.WriteString(text)
	message.WriteString("\n\n本机附件：")
	for _, input := range inputs {
		message.WriteString("\n- ")
		message.WriteString(input.Path)
	}
	return s.Submit(id, message.String())
}
func (s *Service) attachedFile(t domain.Task, p string) (bool, error) {
	var attachment localAttachment
	err := s.Store.Load("local_inputs:"+t.ID, domain.Digest(p), &attachment)
	if errors.Is(err, sql.ErrNoRows) {
		return false, nil
	}
	if err != nil {
		return false, err
	}
	return attachment.GrantID == t.Grant.ID && attachment.Path == p, nil
}
